name: Lint and Test PR

on: pull_request

env:
  NX_BASE: ${{github.base_ref}}
  NX_HEAD: ${{github.head_ref}}

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
      # TODO: Check for optimally cloning git repo in CI
      - name: setup repo
        uses: actions/checkout@v4

      - name: setup pnpm
        uses: pnpm/action-setup@v3

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
          cache: 'pnpm'

      - name: log Params
        run: |
          echo NX_BASE = $NX_BASE
          echo NX_HEAD = $NX_HEAD
          echo node version = $(node --version)
          echo pnpm version = $(pnpm --version)

      - name: install
        run: pnpm i

      - name: build
        run: pnpm build

      - name: lint check
        run: pnpm lint:check

      - name: format check
        run: pnpm format:check

      - name: test
        run: pnpm test
