name: Lint and Test PR

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited
      - ready_for_review

env:
  NX_BASE: origin/${{github.base_ref}}
  NX_HEAD: ${{github.head_ref}}

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
  lint-test:
    runs-on: ubuntu-latest

    steps:
      # TODO: Check for optimally cloning git repo in CI
      - name: setup repo
        uses: actions/checkout@v4

      - name: setup pnpm
        uses: pnpm/action-setup@v3

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
          cache: "pnpm"

      - name: log Params
        run: |
          echo NX_BASE = $NX_BASE
          echo NX_HEAD = $NX_HEAD
          echo node version = $(node --version)
          echo pnpm version = $(pnpm --version)

      - name: install
        run: pnpm i

      - name: build
        run: pnpm build

      - name: lint check
        run: pnpm lint:check

      - name: format check
        run: pnpm format:check

      - name: test
        run: pnpm test
